name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t certifiedtboy/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
<<<<<<< HEAD
      - run: docker push certifiedtboy/auth
=======
      - run: docker tag certifiedtboy/auth
>>>>>>> a9fd0775ae057378ba00d031583d0213efd9bed0
